PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX atlasterms: <http://rdf.ebi.ac.uk/terms/atlas/>

SELECT DISTINCT ?condition ?condLabel (count (?protein) AS ?proteinCount) 
WHERE 
{
  ?specimen 
    atlasterms:dbXref ?protein;
    atlasterms:hasFactorValue ?condition.
    
  ?condition rdfs:subClassOf ?searchCondition;
    rdfs:label ?condLabel.
}
GROUP BY ?condition ?condLabel
ORDER BY DESC ( ?proteinCount )
LIMIT 100